package database

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	_ "github.com/mattn/go-sqlite3"
)

// ResolveSyncthingConflicts scans the directory containing dbPath for matching .sync-conflict-*.db files,
// safely merges all unique missing records into dbPath using INSERT OR IGNORE, and removes the conflict files.
func ResolveSyncthingConflicts(dbPath string) error {
	dir := filepath.Dir(dbPath)
	baseName := filepath.Base(dbPath)
	ext := filepath.Ext(baseName)
	nameWithoutExt := strings.TrimSuffix(baseName, ext)

	pattern := filepath.Join(dir, fmt.Sprintf("%s.sync-conflict-*%s", nameWithoutExt, ext))
	conflictFiles, err := filepath.Glob(pattern)
	if err != nil || len(conflictFiles) == 0 {
		return nil
	}

	log.Printf("[Syncthing Resolver] Found %d conflict file(s) for %s", len(conflictFiles), dbPath)

	mainDB, err := sql.Open("sqlite3", fmt.Sprintf("file:%s?_foreign_keys=off&_journal_mode=DELETE&_busy_timeout=5000", dbPath))
	if err != nil {
		return fmt.Errorf("failed to open main db for sync conflict resolution: %w", err)
	}
	defer mainDB.Close()

	// Retrieve list of non-system tables from the main database
	rows, err := mainDB.Query("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
	if err != nil {
		return fmt.Errorf("failed to query main db tables: %w", err)
	}
	var tables []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err == nil {
			tables = append(tables, name)
		}
	}
	rows.Close()

	for _, confFile := range conflictFiles {
		if strings.HasSuffix(confFile, "-wal") || strings.HasSuffix(confFile, "-shm") {
			continue
		}

		log.Printf("[Syncthing Resolver] Merging conflict file: %s", confFile)

		confConn, err := sql.Open("sqlite3", fmt.Sprintf("file:%s?mode=ro", confFile))
		if err != nil {
			log.Printf("[Syncthing Resolver] Could not open %s (skipping): %v", confFile, err)
			continue
		}

		success := true
		for _, table := range tables {
			// Check table existence in conflict DB
			var count int
			err := confConn.QueryRow("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?", table).Scan(&count)
			if err != nil || count == 0 {
				continue
			}

			// Get matching column names
			colRows, err := confConn.Query(fmt.Sprintf("PRAGMA table_info(%s)", table))
			if err != nil {
				continue
			}
			var cols []string
			for colRows.Next() {
				var cid int
				var name, ctype string
				var notnull int
				var dflt sql.NullString
				var pk int
				if err := colRows.Scan(&cid, &name, &ctype, &notnull, &dflt, &pk); err == nil {
					cols = append(cols, name)
				}
			}
			colRows.Close()

			if len(cols) == 0 {
				continue
			}

			colList := strings.Join(cols, ", ")
			placeholders := strings.Repeat("?, ", len(cols))
			placeholders = placeholders[:len(placeholders)-2]

			// Read rows from conflict DB
			confRows, err := confConn.Query(fmt.Sprintf("SELECT %s FROM %s", colList, table))
			if err != nil {
				continue
			}

			insertStmt := fmt.Sprintf("INSERT OR IGNORE INTO %s (%s) VALUES (%s)", table, colList, placeholders)
			stmt, err := mainDB.Prepare(insertStmt)
			if err != nil {
				confRows.Close()
				continue
			}

			for confRows.Next() {
				values := make([]interface{}, len(cols))
				valuePointers := make([]interface{}, len(cols))
				for i := range values {
					valuePointers[i] = &values[i]
				}

				if err := confRows.Scan(valuePointers...); err == nil {
					_, _ = stmt.Exec(values...)
				}
			}
			stmt.Close()
			confRows.Close()
		}

		confConn.Close()

		if success {
			_ = os.Remove(confFile)
			_ = os.Remove(confFile + "-wal")
			_ = os.Remove(confFile + "-shm")
			log.Printf("[Syncthing Resolver] Successfully merged and removed %s", confFile)
		}
	}

	// Post-merge touchups for app.db to keep chat sorting and contacts up to date
	if baseName == "app.db" {
		_, _ = mainDB.Exec(`
			UPDATE contacts
			SET last_message_at = (
				SELECT MAX(timestamp)
				FROM messages
				WHERE messages.chat_jid = contacts.jid OR messages.chat_jid = contacts.lid
			)
			WHERE EXISTS (
				SELECT 1 FROM messages WHERE messages.chat_jid = contacts.jid OR messages.chat_jid = contacts.lid
			)
		`)
		_, _ = mainDB.Exec(`
			INSERT INTO contacts (jid, last_message_at)
			SELECT chat_jid, MAX(timestamp)
			FROM messages
			WHERE chat_jid IS NOT NULL AND chat_jid != '' AND chat_jid NOT IN (SELECT jid FROM contacts)
			GROUP BY chat_jid
		`)
	}

	return nil
}

// CleanStaleConflictFiles removes binary and git conflict files generated by Syncthing.
func CleanStaleConflictFiles(dir string) {
	patterns := []string{
		filepath.Join(dir, "whats-gtk*.sync-conflict-*"),
		filepath.Join(dir, "*.sync-conflict-*.db-wal"),
		filepath.Join(dir, "*.sync-conflict-*.db-shm"),
		filepath.Join(dir, "*.sync-conflict-*.go"),
		filepath.Join(dir, "*", "*.sync-conflict-*.go"),
		filepath.Join(dir, ".git", "*.sync-conflict-*"),
		filepath.Join(dir, ".git", "refs", "heads", "*.sync-conflict-*"),
		filepath.Join(dir, ".git", "logs", "refs", "heads", "*.sync-conflict-*"),
		filepath.Join(dir, ".git", "logs", "refs", "remotes", "origin", "*.sync-conflict-*"),
	}

	for _, pattern := range patterns {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			continue
		}
		for _, m := range matches {
			if fi, err := os.Stat(m); err == nil && !fi.IsDir() {
				_ = os.Remove(m)
				log.Printf("[Syncthing Resolver] Removed stale conflict file: %s", m)
			}
		}
	}
}
